Use Bouncycastle to read encrypted PKCS 8 keys
PBES2 support is broken in the JDK and causing exceptions like

    java.lang.ClassCastException: org.bouncycastle.asn1.DLSequence cannot be cast to org.bouncycastle.asn1.ASN1Integer
        at org.bouncycastle.asn1.pkcs.PrivateKeyInfo.<init>(PrivateKeyInfo.java:79)
        at org.bouncycastle.asn1.pkcs.PrivateKeyInfo.getInstance(PrivateKeyInfo.java:45)
        at com.android.signapk.SignApk.readPrivateKey(SignApk.java:271)
        at com.android.signapk.SignApk.main(SignApk.java:1105)

or more specifically:

    java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
        at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:253)
        at sun.security.util.DerInputStream.getOID(DerInputStream.java:314)
        at com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:267)
        at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
        at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
        at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
        at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
        at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:95)
        at com.android.signapk.SignApk.decryptPrivateKey(SignApk.java:228)
        at com.android.signapk.SignApk.readPrivateKey(SignApk.java:260)
        at com.android.signapk.SignApk.main(SignApk.java:1106)

A JDK bugs exists at https://bugs.openjdk.java.net/browse/JDK-8076999
but there hasn't been any recent activity/nor a suggested fix.

Use BouncyCastle to read and decrypt the encrypted key which is
working fine. However, Android's version of BouncyCastle doesn't
include the necessary classes. Since this is only run on the host,
just use the upstream version of BouncyCastle.